import{a as b,S as L,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const w="52825058-9c2b701d3fa996d89232a6d0f",x="https://pixabay.com/api/";async function u(o,r=1){try{return(await b(x,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw console.log(e.message),e}}const f=document.querySelector(".gallery"),S=new L(".gallery a"),h=document.querySelector(".loader"),m=document.querySelector(".button-load");function p(o){if(!o){console.error("Expected array, got:",o);return}const r=o.map(e=>`
    <li class="photo-card"> 
    <a href="${e.largeImageURL}">
    <img class="imgs" src="${e.webformatURL}" alt="${e.tags}" />
    </a>
          <div class="info">
          <p class="likes"> <b>Likes</b> ${e.likes}</p>
           <p class="views"> <b>Views</b>${e.views}</p>
            <p class="comments"> <b>Comments</b>${e.comments}</p>
             <p class="downloads"> <b>Downloads</b>${e.downloads}</p>
          </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),S.refresh()}function v(o){f.innerHTML=""}function g(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}function C(){m.classList.replace("load-more-hidden","load-more")}function E(){m.classList.replace("load-more","load-more-hidden")}const q=document.querySelector(".form"),d=document.querySelector(".button-load");let c=1,y="";q.addEventListener("submit",M);function M(o){o.preventDefault(),v();const r=o.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",maxWidth:"330px"});return}y=r,g(),u(r).then(e=>{e.hits.length===0?(console.log("Empty search detected"),n.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",theme:"light",maxWidth:"330px",color:"white"})):(p(e.hits),C())}).catch(e=>{console.error("Something went wrong"),n.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}).finally(()=>{o.target.reset(),l()})}d.addEventListener("click",P);async function P(){c++,d.disabled=!0,g();try{const o=await u(y,c);p(o.hits),l();const r=Math.ceil(o.totalHits/15);c>=r&&(E(),n.info({message:"You have reached the end of search results.",position:"topRight",backgroundColor:"#4092efff",messageColor:"#fff",maxWidth:"330px"}));const a=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({left:0,top:a.height,behavior:"smooth"})}catch(o){alert(o.message)}finally{l(),d.disabled=!1}}
//# sourceMappingURL=index.js.map
