import{a as w,S as L,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=e(o);fetch(o.href,s)}})();const x="52825058-9c2b701d3fa996d89232a6d0f",S="https://pixabay.com/api/";async function l(t,r=1){try{return(await w(S,{params:{key:x,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw console.log(e.message),e}}const f=document.querySelector(".gallery"),C=new L(".gallery a"),u=document.querySelector(".loader"),h=document.querySelector(".button-load");function m(t){if(!t){console.error("Expected array, got:",t);return}const r=t.map(e=>`
    <li class="photo-card"> 
    <a href="${e.largeImageURL}">
    <img class="imgs" src="${e.webformatURL}" alt="${e.tags}" />
    </a>
          <div class="info">
          <p class="likes"> <b>Likes</b> ${e.likes}</p>
           <p class="views"> <b>Views</b>${e.views}</p>
            <p class="comments"> <b>Comments</b>${e.comments}</p>
             <p class="downloads"> <b>Downloads</b>${e.downloads}</p>
          </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),C.refresh()}function v(t){f.innerHTML=""}function p(){u.classList.remove("hidden")}function g(){u.classList.add("hidden")}function y(){h.classList.replace("load-more-hidden","load-more")}function E(){h.classList.replace("load-more","load-more-hidden")}const q=document.querySelector(".form"),d=document.querySelector(".button-load");let n=1,b="";q.addEventListener("submit",M);async function M(t){t.preventDefault(),v();const r=t.target.elements["search-text"].value.trim();if(!r){a.warning({message:"Please enter a search term!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",maxWidth:"330px"});return}b=r,n=1,p(),l(r);try{const e=await l(r,n);e.hits.length===0?(console.log("Empty search detected"),a.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",theme:"light",maxWidth:"330px",color:"white"})):(m(e.hits),y())}catch{console.error("Something went wrong"),a.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}finally{g()}}d.addEventListener("click",R);async function R(){n++,d.disabled=!0,p();try{const t=await l(b,n);m(t.hits);const r=Math.ceil(t.totalHits/15);n<r?y():(E(),a.info({message:"You have reached the end of search results.",position:"topRight",backgroundColor:"#4092efff",messageColor:"#fff",maxWidth:"330px"}));const i=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({left:0,top:i.height*2,behavior:"smooth"})}catch{a.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}finally{g(),d.disabled=!1}}
//# sourceMappingURL=index.js.map
