import{a as L,S as x,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(o){if(o.ep)return;o.ep=!0;const s=e(o);fetch(o.href,s)}})();const C="52825058-9c2b701d3fa996d89232a6d0f",S="https://pixabay.com/api/";async function f(t,r=1){try{return(await L(S,{params:{key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw console.log(e.message),e}}const u=document.querySelector(".gallery"),v=new x(".gallery a"),h=document.querySelector(".loader"),m=document.querySelector(".button-load");function p(t){if(!t){console.error("Expected array, got:",t);return}const r=t.map(e=>`
    <li class="photo-card"> 
    <a href="${e.largeImageURL}">
    <img class="imgs" src="${e.webformatURL}" alt="${e.tags}" />
    </a>
          <div class="info">
          <p class="likes"> <b>Likes</b> ${e.likes}</p>
           <p class="views"> <b>Views</b>${e.views}</p>
            <p class="comments"> <b>Comments</b>${e.comments}</p>
             <p class="downloads"> <b>Downloads</b>${e.downloads}</p>
          </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()}function E(t){u.innerHTML=""}function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function b(){m.classList.replace("load-more-hidden","load-more")}function d(){m.classList.replace("load-more","load-more-hidden")}const M=document.querySelector(".form"),i=document.querySelector(".button-load");let c=1,w="";M.addEventListener("submit",R);async function R(t){t.preventDefault(),E();const r=t.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",maxWidth:"330px"});return}w=r,c=1,d(),i.disabled=!0,g();try{const e=await f(r,c);if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",theme:"light",maxWidth:"330px",color:"white"});return}p(e.hits);const a=Math.ceil(e.totalHits/15);c<a?(b(),i.disabled=!1):(d(),n.info({message:"You have reached the end of search results.",position:"topRight",backgroundColor:"#4092efff",messageColor:"#fff",maxWidth:"330px"}))}catch{console.error("Something went wrong"),n.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}finally{y()}}i.addEventListener("click",q);async function q(){c++,i.disabled=!0,g();try{const t=await f(w,c);p(t.hits);const r=Math.ceil(t.totalHits/15);c<r?(b(),i.disabled=!1):(d(),n.info({message:"You have reached the end of search results.",position:"topRight",backgroundColor:"#4092efff",messageColor:"#fff",maxWidth:"330px"}));const a=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({left:0,top:a.height*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}finally{y(),i.disabled=!1}}
//# sourceMappingURL=index.js.map
